# Generated by Django 3.2.8 on 2021-11-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=20)),
                ('queries', models.TextField(max_length=1000)),
            ],
        ),
    ]
